[[exercises]]
name = "pending_test_exercise"
path = "pending_test_exercise.rs"
mode = "test"
hint = """"""

[[exercises]]
name = "pending_exercise"
path = "exercises/pending_exercise.rs"
mode = "compile"
hint = """"""

