[[exercises]]
name = "hello_world"
path = "exercises/hello_world.rs"
mode = "compile"
hint = """"""

[[exercises]]
name = "exercise_with_tests"
path = "exercises/exercise_with_tests.rs"
mode = "compile"
hint = """"""